# Generated by Django 2.1.7 on 2019-03-18 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allrecipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, default='default.gif', upload_to='post_pics'),
        ),
    ]
