# Generated by Django 2.1.7 on 2019-03-18 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allrecipes', '0002_auto_20190318_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default='default.gif', upload_to='post_pics'),
        ),
    ]
