# Generated by Django 2.1.7 on 2019-03-12 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allrecipes', '0003_recipe_publish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='publish',
            field=models.BooleanField(default=True),
        ),
    ]
