# Generated by Django 2.1.7 on 2019-03-13 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allrecipes', '0004_auto_20190312_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='publish',
            field=models.BooleanField(default=False),
        ),
    ]
