# Generated by Django 2.1.7 on 2019-03-14 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allrecipes', '0005_auto_20190313_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default='default.gif', upload_to='recipe_pic'),
        ),
    ]
